export const accessContent = {
  heading: {
    eyebrow: "Conta e colaboração",
    title: "Pessoas e acessos",
    description:
      "Organize seus espaços financeiros, convide pessoas de confiança e controle exatamente o que cada uma pode visualizar ou alterar.",
    invite: "Convidar pessoa",
    createWorkspace: "Novo espaço",
  },
  summary: {
    workspaces: "Espaços financeiros",
    workspacesHelper: "Pessoal e compartilhados",
    members: "Pessoas com acesso",
    membersHelper: "Considerando todos os espaços",
    invitations: "Convites pendentes",
    invitationsHelper: "Aguardando confirmação",
    currentRole: "Seu acesso atual",
    currentRoleHelper: "No espaço selecionado",
  },
  roles: {
    owner: "Proprietário",
    editor: "Editor",
    viewer: "Somente leitura",
  },
  workspaceKinds: {
    personal: "Espaço pessoal",
    shared: "Espaço compartilhado",
  },
  workspaces: {
    title: "Seus espaços",
    description: "Alterne entre organizações financeiras sem misturar dados.",
    selected: "Selecionado",
    members: "pessoas",
    member: "pessoa",
    lastActivity: "Última atividade",
    switchAction: "Acessar espaço",
    currentAction: "Espaço atual",
    empty: "Nenhum espaço financeiro disponível.",
  },
  accessOverview: {
    title: "Como funciona o compartilhamento",
    description:
      "Cada pessoa entra com a própria conta. Você escolhe o papel e pode alterar ou remover o acesso a qualquer momento.",
    privateTitle: "Senhas continuam privadas",
    privateDescription:
      "Ninguém precisa usar seu e-mail ou sua senha para acessar um espaço compartilhado.",
    separatedTitle: "Dados separados por espaço",
    separatedDescription:
      "Lançamentos pessoais não aparecem em espaços compartilhados e vice-versa.",
    controlledTitle: "Permissões claras",
    controlledDescription:
      "Proprietários administram tudo, editores organizam as finanças e leitores apenas consultam.",
  },
  members: {
    title: "Pessoas do espaço",
    description: "Gerencie quem participa do espaço atualmente selecionado.",
    searchPlaceholder: "Buscar por nome ou e-mail",
    name: "Pessoa",
    role: "Permissão",
    joinedAt: "Entrou em",
    lastAccess: "Último acesso",
    actions: "Ações",
    you: "Você",
    changeRole: "Alterar permissão",
    remove: "Remover acesso",
    ownerProtected: "O proprietário não pode ser removido.",
    noResults: "Nenhuma pessoa encontrada com essa busca.",
  },
  invitations: {
    title: "Convites enviados",
    description: "Acompanhe convites que ainda não foram aceitos.",
    email: "E-mail",
    role: "Permissão",
    sentAt: "Enviado em",
    expiresAt: "Expira em",
    status: "Situação",
    actions: "Ações",
    pending: "Pendente",
    accepted: "Aceito",
    expired: "Expirado",
    revoked: "Cancelado",
    resend: "Reenviar",
    cancel: "Cancelar",
    empty: "Não existem convites para este espaço.",
  },
  permissions: {
    title: "Matriz de permissões",
    description: "Veja rapidamente o que cada nível de acesso pode fazer.",
    permission: "Permissão",
    allowed: "Permitido",
    denied: "Não permitido",
    items: {
      viewDashboard: {
        label: "Visualizar dashboard e relatórios",
        description: "Consultar saldos, lançamentos e análises do espaço.",
      },
      manageTransactions: {
        label: "Criar e editar movimentações",
        description: "Adicionar receitas, despesas, transferências e compromissos.",
      },
      managePlanning: {
        label: "Gerenciar planejamento",
        description: "Alterar orçamentos, metas, dívidas e assinaturas.",
      },
      manageMembers: {
        label: "Gerenciar pessoas e convites",
        description: "Convidar, alterar permissões e remover participantes.",
      },
      exportData: {
        label: "Exportar informações",
        description: "Gerar relatórios, planilhas e cópias dos dados.",
      },
      deleteWorkspace: {
        label: "Excluir o espaço financeiro",
        description: "Remover definitivamente o espaço e seus dados.",
      },
    },
  },
  inviteDialog: {
    title: "Convidar uma pessoa",
    description:
      "Ela receberá um convite para acessar o espaço com a própria conta.",
    workspace: "Espaço financeiro",
    email: "E-mail da pessoa",
    emailPlaceholder: "pessoa@exemplo.com",
    role: "Permissão inicial",
    editorDescription: "Pode criar, editar e organizar informações financeiras.",
    viewerDescription: "Pode consultar os dados, sem realizar alterações.",
    cancel: "Cancelar",
    submit: "Enviar convite",
    invalidEmail: "Informe um endereço de e-mail válido.",
    duplicateEmail: "Esta pessoa já participa ou possui um convite pendente.",
  },
  roleDialog: {
    title: "Alterar permissão",
    description: "Escolha o novo nível de acesso para esta pessoa.",
    cancel: "Cancelar",
    submit: "Salvar permissão",
  },
  workspaceDialog: {
    title: "Criar espaço compartilhado",
    description:
      "Use um espaço separado para finanças familiares, viagens ou outro planejamento conjunto.",
    name: "Nome do espaço",
    namePlaceholder: "Ex.: Finanças da família",
    descriptionLabel: "Descrição",
    descriptionPlaceholder: "Explique brevemente o objetivo deste espaço.",
    cancel: "Cancelar",
    submit: "Criar espaço",
    required: "Informe um nome para o espaço.",
  },
  feedback: {
    invited: "Convite enviado com sucesso.",
    roleChanged: "Permissão atualizada.",
    memberRemoved: "Acesso removido.",
    invitationResent: "Convite reenviado.",
    invitationCanceled: "Convite cancelado.",
    workspaceCreated: "Novo espaço financeiro criado.",
    workspaceChanged: "Espaço financeiro alterado.",
  },
  accessibility: {
    summary: "Resumo de acessos",
    closeDialog: "Fechar janela",
    currentWorkspace: "Espaço financeiro atual",
  },
} as const;

export const authContent = {
  brand: {
    name: "Finanças",
    tagline: "Sua vida financeira organizada em um só lugar.",
  },
  panel: {
    eyebrow: "Controle financeiro pessoal",
    title: "Clareza para cuidar do seu dinheiro todos os dias.",
    description:
      "Acompanhe contas, cartões, metas e compromissos sem planilhas espalhadas e sem compartilhar senhas.",
    benefits: [
      "Organização completa das finanças pessoais",
      "Espaços privados ou compartilhados",
      "Permissões individuais para cada pessoa",
    ],
    privacy: "Seus dados financeiros permanecem privados.",
  },
  login: {
    eyebrow: "Bem-vindo de volta",
    title: "Entre na sua conta",
    description: "Acesse seus espaços financeiros e continue sua organização.",
    email: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    password: "Senha",
    passwordPlaceholder: "Digite sua senha",
    remember: "Manter conectado neste dispositivo",
    forgot: "Esqueci minha senha",
    submit: "Entrar",
    google: "Entrar com Google",
    divider: "ou continue com e-mail",
    noAccount: "Ainda não possui uma conta?",
    register: "Criar conta gratuita",
    invalid: "Preencha um e-mail válido e uma senha com pelo menos 8 caracteres.",
    demoNote: "Nesta fase, o acesso funciona em modo demonstrativo no navegador.",
  },
  register: {
    eyebrow: "Comece sua organização",
    title: "Crie sua conta",
    description: "Seu primeiro espaço financeiro pessoal será criado automaticamente.",
    name: "Nome completo",
    namePlaceholder: "Seu nome",
    email: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    password: "Senha",
    passwordPlaceholder: "Mínimo de 8 caracteres",
    confirmation: "Confirmar senha",
    confirmationPlaceholder: "Digite a senha novamente",
    termsPrefix: "Concordo com os",
    terms: "Termos de Uso",
    privacyConnector: "e com a",
    privacy: "Política de Privacidade",
    submit: "Criar minha conta",
    google: "Criar conta com Google",
    divider: "ou cadastre-se com e-mail",
    hasAccount: "Já possui uma conta?",
    login: "Entrar",
    invalid: "Revise os campos obrigatórios antes de continuar.",
    passwordMismatch: "As senhas informadas não são iguais.",
  },
  recovery: {
    eyebrow: "Recuperação de acesso",
    title: "Redefina sua senha",
    description: "Informe seu e-mail para receber as instruções de recuperação.",
    email: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    submit: "Enviar instruções",
    back: "Voltar para o login",
    invalid: "Informe um endereço de e-mail válido.",
    successTitle: "Confira sua caixa de entrada",
    successDescription:
      "Enviamos as instruções de recuperação para o endereço informado.",
    sendAgain: "Enviar novamente",
  },
  invitation: {
    eyebrow: "Convite para colaborar",
    title: "Você foi convidado para um espaço financeiro",
    description:
      "Aceite o convite para acessar o espaço com sua própria conta e a permissão definida pelo proprietário.",
    invitedBy: "Convidado por",
    workspace: "Espaço",
    permission: "Permissão",
    expires: "Validade do convite",
    accept: "Aceitar convite",
    decline: "Agora não",
    loginNote: "Ao aceitar, você será direcionado para o gerenciamento de acessos.",
    invalidTitle: "Convite indisponível",
    invalidDescription: "Este convite não existe, expirou ou já foi utilizado.",
    goLogin: "Ir para o login",
  },
  validation: {
    validEmail: "Informe um endereço de e-mail válido.",
  },
} as const;
