import type {
  BillingCycle,
  ChargeStatus,
  SubscriptionCategory,
  SubscriptionStatus,
  UsageFrequency,
} from "@/types/assinaturas";

export const subscriptionsContent = {
  heading: {
    eyebrow: "Custos recorrentes",
    title: "Assinaturas e cobranças",
    description:
      "Centralize serviços recorrentes, acompanhe reajustes e identifique gastos que podem ser reduzidos.",
    newCharge: "Registrar cobrança",
    newSubscription: "Nova assinatura",
  },
  summary: {
    monthly: "Custo mensal equivalente",
    annual: "Estimativa anual",
    nextThirtyDays: "Próximos 30 dias",
    active: "Assinaturas ativas",
    savings: "Economia possível",
    monthlyHelper: "Média considerando todos os ciclos",
    annualHelper: "Projeção para os próximos 12 meses",
    nextThirtyDaysHelper: "Cobranças previstas no período",
    activeSingular: "serviço ativo",
    activePlural: "serviços ativos",
    savingsHelper: "Serviços com baixo uso ou em teste",
    attention: "Revisar",
  },
  toolbar: {
    subscriptions: "Assinaturas",
    charges: "Histórico de cobranças",
    searchPlaceholder: "Buscar serviço, fornecedor ou observação",
    categoryLabel: "Categoria",
    statusLabel: "Status",
    accountLabel: "Conta",
    allCategories: "Todas as categorias",
    allStatuses: "Todos os status",
    allAccounts: "Todas as contas",
    clear: "Limpar filtros",
  },
  list: {
    eyebrow: "Serviços cadastrados",
    title: "Suas assinaturas",
    resultSingular: "assinatura encontrada",
    resultPlural: "assinaturas encontradas",
    emptyTitle: "Nenhuma assinatura encontrada",
    emptyDescription: "Ajuste os filtros ou cadastre um novo serviço recorrente.",
    unknownAccount: "Conta não identificada",
    perWeek: "por semana",
    perMonth: "por mês",
    perQuarter: "a cada 3 meses",
    perSemester: "a cada 6 meses",
    perYear: "por ano",
    monthlyEquivalent: "Equivale a",
    nextCharge: "Próxima cobrança",
    trialEnds: "Teste termina em",
    autoRenew: "Renovação automática",
    manualRenew: "Renovação manual",
    priceIncrease: "Reajuste de",
    since: "desde",
    usage: "Uso informado",
    recordCharge: "Registrar cobrança",
    edit: "Editar",
    pause: "Pausar",
    resume: "Retomar",
    cancel: "Cancelar assinatura",
    cancelled: "Assinatura cancelada",
  },
  insights: {
    breakdownEyebrow: "Distribuição dos custos",
    breakdownTitle: "Custo mensal por categoria",
    breakdownEmpty: "Cadastre assinaturas ativas para visualizar a distribuição.",
    upcomingEyebrow: "Agenda de cobranças",
    upcomingTitle: "Próximos vencimentos",
    upcomingEmpty: "Nenhuma cobrança prevista nos próximos 30 dias.",
    opportunitiesEyebrow: "Oportunidades de economia",
    opportunitiesTitle: "Serviços para revisar",
    lowUsage: "Uso baixo informado",
    trialEnding: "Período de teste perto do fim",
    priceChanged: "Valor reajustado recentemente",
    noOpportunities: "Nenhum serviço exige revisão neste momento.",
    estimatedSaving: "Economia mensal potencial",
    daysSingular: "dia",
    daysPlural: "dias",
    today: "Hoje",
    overdue: "Em atraso",
  },
  charges: {
    eyebrow: "Movimentações recorrentes",
    title: "Histórico de cobranças",
    resultSingular: "cobrança registrada",
    resultPlural: "cobranças registradas",
    date: "Data",
    subscription: "Assinatura",
    account: "Conta utilizada",
    status: "Status",
    amount: "Valor",
    note: "Observação",
    emptyTitle: "Nenhuma cobrança encontrada",
    emptyDescription: "As cobranças registradas aparecerão aqui para consulta.",
    removedSubscription: "Assinatura removida",
  },
  subscriptionDialog: {
    createTitle: "Cadastrar nova assinatura",
    createDescription: "Adicione um serviço recorrente para acompanhar os próximos custos.",
    editTitle: "Editar assinatura",
    editDescription: "Atualize valores, datas, uso ou condições de renovação.",
    name: "Nome do serviço",
    namePlaceholder: "Ex.: streaming, academia ou armazenamento",
    provider: "Fornecedor",
    providerPlaceholder: "Ex.: Netflix, academia ou operadora",
    category: "Categoria",
    amount: "Valor da cobrança",
    billingCycle: "Periodicidade",
    nextChargeDate: "Próxima cobrança",
    account: "Conta de pagamento",
    status: "Status",
    startDate: "Data de início",
    trialEndsAt: "Fim do período de teste",
    previousAmount: "Valor anterior",
    priceChangedAt: "Data do reajuste",
    usage: "Frequência de uso",
    autoRenew: "Renovação automática",
    notes: "Observações",
    notesPlaceholder: "Ex.: plano familiar, fidelidade, cancelamento pelo aplicativo ou benefício incluso.",
    cancel: "Cancelar",
    create: "Cadastrar assinatura",
    save: "Salvar alterações",
    requiredError: "Preencha os campos obrigatórios para continuar.",
    amountError: "Informe um valor de cobrança maior que zero.",
    previousAmountError: "O valor anterior não pode ser maior que o valor atual sem uma observação de redução.",
    successCreate: "Assinatura cadastrada com sucesso.",
    successEdit: "Assinatura atualizada com sucesso.",
  },
  chargeDialog: {
    title: "Registrar cobrança",
    description: "Confirme uma cobrança paga, agendada ou ignorada.",
    subscription: "Assinatura",
    date: "Data da cobrança",
    amount: "Valor",
    account: "Conta utilizada",
    status: "Situação",
    note: "Observação",
    notePlaceholder: "Ex.: cobrança mensal, renovação anual ou serviço não cobrado.",
    expectedAmount: "Valor previsto",
    nextCharge: "Próxima cobrança cadastrada",
    cancel: "Cancelar",
    confirm: "Confirmar cobrança",
    requiredError: "Selecione a assinatura, a conta e informe os dados da cobrança.",
    amountError: "O valor deve ser maior que zero, exceto quando a cobrança for ignorada.",
    success: "Cobrança registrada e próxima data atualizada.",
    defaultNote: "Cobrança recorrente",
  },
  feedback: {
    paused: "Assinatura pausada.",
    resumed: "Assinatura retomada.",
    cancelled: "Assinatura cancelada.",
  },
  accessibility: {
    summary: "Resumo das assinaturas",
    viewTabs: "Visualização das assinaturas",
    search: "Buscar assinaturas",
    closeDialog: "Fechar janela",
    subscriptionActions: "Ações da assinatura",
  },
  categories: {
    streaming: "Streaming e entretenimento",
    software: "Aplicativos e software",
    health: "Saúde e bem-estar",
    education: "Educação",
    utilities: "Serviços essenciais",
    insurance: "Seguros e proteção",
    membership: "Clubes e associações",
    other: "Outros serviços",
  } satisfies Record<SubscriptionCategory, string>,
  statuses: {
    active: "Ativa",
    trial: "Em teste",
    paused: "Pausada",
    cancelled: "Cancelada",
  } satisfies Record<SubscriptionStatus, string>,
  billingCycles: {
    weekly: "Semanal",
    monthly: "Mensal",
    quarterly: "Trimestral",
    semiannual: "Semestral",
    annual: "Anual",
  } satisfies Record<BillingCycle, string>,
  usages: {
    high: "Uso frequente",
    medium: "Uso moderado",
    low: "Uso baixo",
    unknown: "Ainda não informado",
  } satisfies Record<UsageFrequency, string>,
  chargeStatuses: {
    paid: "Paga",
    scheduled: "Agendada",
    overdue: "Em atraso",
    skipped: "Ignorada",
  } satisfies Record<ChargeStatus, string>,
} as const;
