import type {
  CalendarEventRecurrence,
  CalendarEventStatus,
  CalendarEventType,
} from "@/types/calendario";

export const calendarContent = {
  heading: {
    eyebrow: "Planejamento por data",
    title: "Calendário financeiro",
    description:
      "Reúna vencimentos, recebimentos, faturas e reservas em uma agenda mensal para antecipar o impacto de cada compromisso.",
    newAction: "Novo compromisso",
  },
  summary: {
    ariaLabel: "Resumo do calendário financeiro",
    income: "Entradas previstas",
    incomeHelper: "Recebimentos do mês exibido",
    expenses: "Saídas previstas",
    expensesHelper: "Contas, faturas e reservas",
    result: "Resultado previsto",
    resultHelper: "Entradas menos compromissos",
    commitments: "Compromissos",
    commitmentsHelper: "Eventos financeiros no período",
    overdue: "Em atraso",
    overdueHelper: "Itens que exigem atenção",
  },
  toolbar: {
    ariaLabel: "Controles do calendário",
    periodLabel: "Período exibido",
    typeLabel: "Tipo",
    statusLabel: "Status",
    accountLabel: "Conta",
    viewAriaLabel: "Modo de visualização",
    previousMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    today: "Hoje",
    monthView: "Mês",
    agendaView: "Agenda",
    allTypes: "Todos os tipos",
    allStatuses: "Todos os status",
    allAccounts: "Todas as contas",
  },
  weekdays: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
  calendar: {
    ariaLabel: "Calendário mensal",
    dayAriaSuffix: "compromissos",
    moreEvents: "outros",
    emptyDay: "Nenhum compromisso financeiro nesta data.",
    today: "Hoje",
  },
  dayPanel: {
    eyebrow: "Agenda do dia",
    income: "Entradas",
    expenses: "Saídas",
    balance: "Resultado do dia",
    markCompleted: "Marcar como concluído",
    completed: "Concluído",
    emptyTitle: "Dia sem movimentações",
    emptyDescription:
      "Selecione outra data ou adicione um compromisso para começar o planejamento.",
  },
  projection: {
    progressAriaSuffix: "dos valores já confirmados",
    eyebrow: "Projeção mensal",
    title: "Como o mês está planejado",
    description:
      "O resultado considera somente os eventos cadastrados no calendário para o período exibido.",
    income: "Total de entradas",
    expenses: "Total de saídas",
    completed: "Já confirmado",
    pending: "Ainda previsto",
    positive: "Previsão positiva",
    negative: "Atenção ao saldo previsto",
  },
  agenda: {
    eyebrow: "Visualização em lista",
    itemSingular: "item",
    itemPlural: "itens",
    title: "Agenda financeira do mês",
    eventsFound: "compromissos encontrados",
    noEventsTitle: "Nenhum compromisso encontrado",
    noEventsDescription:
      "Altere os filtros ou cadastre um novo evento financeiro.",
  },
  dialog: {
    eyebrow: "Agenda financeira",
    title: "Novo compromisso",
    description:
      "Adicione uma entrada, conta, fatura ou reserva prevista para uma data específica.",
    closeAriaLabel: "Fechar cadastro de compromisso",
    fields: {
      title: "Descrição",
      titlePlaceholder: "Ex.: Conta de energia",
      type: "Tipo",
      category: "Categoria",
      amount: "Valor",
      date: "Data",
      account: "Conta relacionada",
      noAccount: "Sem conta definida",
      recurrence: "Recorrência",
      notes: "Observação",
      notesPlaceholder: "Informações adicionais sobre este compromisso",
      currencyPrefix: "R$",
      amountPlaceholder: "0,00",
    },
    cancel: "Cancelar",
    submit: "Adicionar ao calendário",
    success: "Compromisso adicionado ao calendário.",
  },
  validation: {
    required: "Preencha os campos obrigatórios.",
    positiveAmount: "Informe um valor maior que zero.",
  },
  feedback: {
    completed: "Compromisso marcado como concluído.",
  },
  types: {
    income: "Recebimento",
    expense: "Conta a pagar",
    invoice: "Fatura de cartão",
    transfer: "Transferência",
    goal: "Reserva para meta",
    subscription: "Assinatura",
  } satisfies Record<CalendarEventType, string>,
  statuses: {
    scheduled: "Agendado",
    overdue: "Em atraso",
    completed: "Concluído",
  } satisfies Record<CalendarEventStatus, string>,
  recurrences: {
    none: "Não repetir",
    weekly: "Semanal",
    monthly: "Mensal",
    yearly: "Anual",
  } satisfies Record<CalendarEventRecurrence, string>,
  categories: [
    "Moradia",
    "Alimentação",
    "Transporte",
    "Saúde",
    "Educação",
    "Serviços",
    "Vendas",
    "Reembolsos",
    "Cartão de crédito",
    "Assinaturas",
    "Metas e reservas",
    "Transferências",
    "Outros",
  ],
} as const;
