import type {
  CardBrand,
  CardStatus,
  InvoiceStatus,
} from "@/types/cartoes";

export const cardsContent = {
  heading: {
    eyebrow: "Crédito pessoal",
    title: "Cartões e faturas",
    description:
      "Acompanhe limites, fechamento, vencimentos e compras parceladas sem perder de vista os próximos meses.",
    newPurchaseAction: "Nova compra",
    newCardAction: "Novo cartão",
  },
  summary: {
    totalLimit: "Limite total",
    totalLimitHelper: "Soma dos cartões ativos",
    usedLimit: "Limite utilizado",
    usedLimitHelper: "Compras e parcelas ainda comprometidas",
    availableLimit: "Limite disponível",
    availableLimitHelper: "Valor liberado para novas compras",
    openInvoices: "Faturas em aberto",
    openInvoicesHelper: "Total previsto para pagamento",
    futureInstallments: "Parcelas futuras",
    futureInstallmentsHelper: "Compromissos após as faturas atuais",
    usageLabel: "Uso total do limite",
  },
  cards: {
    kicker: "Seus cartões",
    title: "Cartões cadastrados",
    countSuffix: "cartões ativos",
    limit: "Limite",
    available: "Disponível",
    used: "Utilizado",
    closes: "Fecha dia",
    due: "Vence dia",
    primary: "Principal",
    selected: "Cartão selecionado",
    viewInvoice: "Ver fatura",
    ending: "Final",
    emptyTitle: "Nenhum cartão cadastrado",
    emptyDescription:
      "Adicione um cartão para acompanhar faturas, limites e compras parceladas.",
  },
  invoice: {
    kicker: "Fatura selecionada",
    title: "Detalhes da fatura",
    total: "Total da fatura",
    dueDate: "Vencimento",
    closingDate: "Fechamento",
    payAction: "Pagar fatura",
    paidAction: "Fatura paga",
    purchasesTitle: "Compras da fatura",
    purchaseCountSuffix: "lançamentos",
    noPurchasesTitle: "Nenhuma compra nesta fatura",
    noPurchasesDescription:
      "As compras feitas neste período aparecerão aqui automaticamente.",
    installmentLabel: "Parcela",
    singlePurchase: "Compra à vista",
    statuses: {
      open: "Aberta",
      closed: "Fechada",
      paid: "Paga",
    } satisfies Record<InvoiceStatus, string>,
  },
  installments: {
    kicker: "Planejamento futuro",
    title: "Compras parceladas",
    description:
      "Veja quanto do orçamento dos próximos meses já está comprometido.",
    nextCharge: "Próxima cobrança",
    progress: "Parcelas pagas",
    remaining: "Saldo restante",
    emptyTitle: "Nenhuma compra parcelada",
    emptyDescription:
      "Compras divididas em duas ou mais vezes aparecerão nesta área.",
  },
  newCardDialog: {
    eyebrow: "Novo meio de pagamento",
    title: "Adicionar cartão",
    description:
      "Cadastre os dados básicos do cartão para organizar limite e vencimentos.",
    closeAriaLabel: "Fechar cadastro de cartão",
    fields: {
      name: "Nome do cartão",
      namePlaceholder: "Ex.: Cartão principal",
      institution: "Instituição",
      institutionPlaceholder: "Ex.: Nubank",
      lastFourDigits: "Últimos 4 dígitos",
      brand: "Bandeira",
      limit: "Limite total",
      closingDay: "Dia de fechamento",
      dueDay: "Dia de vencimento",
      paymentAccount: "Conta para pagamento",
      style: "Estilo visual",
    },
    cancel: "Cancelar",
    submit: "Salvar cartão",
    success: "Cartão adicionado com sucesso.",
  },
  newPurchaseDialog: {
    eyebrow: "Nova movimentação no crédito",
    title: "Registrar compra",
    description:
      "Adicione uma compra à fatura e acompanhe automaticamente as parcelas futuras.",
    closeAriaLabel: "Fechar cadastro de compra",
    fields: {
      card: "Cartão",
      description: "Descrição",
      descriptionPlaceholder: "Ex.: Compra no mercado",
      category: "Categoria",
      date: "Data da compra",
      amount: "Valor total",
      installments: "Quantidade de parcelas",
    },
    installmentPreview: "Valor aproximado por parcela",
    limitAfterPurchase: "Limite disponível após a compra",
    cancel: "Cancelar",
    submit: "Adicionar à fatura",
    success: "Compra adicionada à fatura.",
  },
  paymentDialog: {
    eyebrow: "Quitação da fatura",
    title: "Pagar fatura",
    description:
      "Confirme a conta utilizada e registre o pagamento desta fatura.",
    closeAriaLabel: "Fechar pagamento da fatura",
    fields: {
      account: "Conta de pagamento",
      date: "Data do pagamento",
      amount: "Valor da fatura",
    },
    note:
      "O pagamento libera o valor da fatura no limite do cartão. A integração com o saldo da conta será consolidada na fase de banco de dados.",
    cancel: "Cancelar",
    submit: "Confirmar pagamento",
    success: "Fatura marcada como paga.",
  },
  brands: {
    visa: "Visa",
    mastercard: "Mastercard",
    elo: "Elo",
  } satisfies Record<CardBrand, string>,
  statuses: {
    active: "Ativo",
    blocked: "Bloqueado",
  } satisfies Record<CardStatus, string>,
  styles: {
    graphite: "Grafite",
    stone: "Claro",
    plum: "Ameixa",
  },
  categories: [
    "Alimentação",
    "Assinaturas",
    "Compras",
    "Educação",
    "Lazer",
    "Saúde",
    "Transporte",
    "Outros",
  ],
  validation: {
    required: "Preencha os campos obrigatórios.",
    positiveAmount: "Informe um valor maior que zero.",
    validDigits: "Informe exatamente os quatro últimos dígitos.",
    validDay: "Os dias de fechamento e vencimento devem estar entre 1 e 28.",
    duplicateCard: "Já existe um cartão com esse nome e final.",
    insufficientLimit: "O limite disponível é insuficiente para esta compra.",
  },
} as const;
