export const settingsContent = {
  heading: {
    eyebrow: "Conta e preferências",
    title: "Configurações",
    description: "Personalize a organização financeira, proteja seu acesso e mantenha cópias dos seus dados.",
    save: "Salvar alterações",
    saved: "Alterações salvas",
  },
  views: {
    profile: "Perfil",
    preferences: "Preferências",
    notifications: "Notificações",
    security: "Segurança",
    activity: "Histórico",
    backups: "Backups",
  },
  summary: {
    account: "Conta principal",
    accountHelper: "Identidade usada nos espaços financeiros",
    protection: "Proteção da conta",
    protectionEnabled: "Proteção reforçada",
    protectionPending: "Ação recomendada",
    protectionHelper: "Alertas de acesso e verificação em duas etapas",
    lastActivity: "Última atividade",
    lastActivityHelper: "Registro mais recente da conta",
    backups: "Backups disponíveis",
    backupsHelper: "Cópias prontas para recuperação",
  },
  profile: {
    title: "Dados do perfil",
    description: "Essas informações identificam você no menu e nos espaços compartilhados.",
    name: "Nome de exibição",
    email: "E-mail de acesso",
    phone: "Telefone",
    timeZone: "Fuso horário",
    initials: "Iniciais",
    identityNote: "O e-mail continuará sendo usado para login e recuperação da conta.",
  },
  preferences: {
    title: "Preferências financeiras",
    description: "Defina como valores, datas e períodos serão apresentados na dashboard.",
    currency: "Moeda padrão",
    locale: "Idioma e região",
    dateFormat: "Formato de data",
    monthStart: "Início do mês financeiro",
    monthStartHelper: "Escolha o dia usado para iniciar cada ciclo financeiro.",
    defaultAccount: "Conta padrão para lançamentos",
    appearance: "Aparência",
    light: "Claro",
    dark: "Escuro",
    system: "Usar o sistema",
    privacyTitle: "Privacidade visual",
    hideBalances: "Ocultar saldos ao abrir a dashboard",
    hideBalancesHelper: "Os valores permanecem protegidos até você escolher revelá-los.",
    compactNumbers: "Resumir valores altos",
    compactNumbersHelper: "Exemplo: R$ 12,5 mil em vez de R$ 12.500,00.",
    brl: "Real brasileiro (R$)",
    brazil: "Português do Brasil",
  },
  notifications: {
    title: "Alertas financeiros",
    description: "Escolha quais acontecimentos precisam chamar sua atenção.",
    billsDue: "Contas próximas do vencimento",
    billsDueHelper: "Receba um aviso antes do vencimento das contas cadastradas.",
    daysBefore: "Avisar com antecedência de",
    receivablesDue: "Recebimentos esperados",
    receivablesDueHelper: "Lembretes de valores previstos e atrasados.",
    budgetAlerts: "Limites de orçamento",
    budgetAlertsHelper: "Avisar quando uma categoria atingir o percentual definido.",
    alertAt: "Alertar ao atingir",
    lowBalance: "Saldo disponível baixo",
    lowBalanceHelper: "Avisar quando o valor disponível ficar abaixo do limite.",
    lowBalanceAmount: "Limite de saldo",
    reportsTitle: "Resumos periódicos",
    weeklySummary: "Resumo semanal",
    weeklySummaryHelper: "Entradas, saídas e compromissos dos próximos sete dias.",
    monthlySummary: "Fechamento mensal",
    monthlySummaryHelper: "Comparação do resultado com o mês anterior.",
    securityAlerts: "Alertas de segurança",
    securityAlertsHelper: "Novos acessos, alterações de senha e sessões encerradas.",
    channelsTitle: "Canais de entrega",
    email: "E-mail",
    browser: "Notificações no navegador",
  },
  security: {
    title: "Segurança da conta",
    description: "Revise as proteções de acesso e os dispositivos conectados.",
    passwordTitle: "Alterar senha",
    currentPassword: "Senha atual",
    newPassword: "Nova senha",
    confirmation: "Confirmar nova senha",
    changePassword: "Atualizar senha",
    passwordRule: "Use pelo menos 8 caracteres, incluindo número e letra.",
    twoFactor: "Verificação em duas etapas",
    twoFactorHelper: "Adiciona um código de confirmação depois da senha.",
    loginAlerts: "Avisos de novo acesso",
    loginAlertsHelper: "Receba um alerta quando um novo navegador entrar na conta.",
    exportProtection: "Confirmar senha antes de exportar",
    exportProtectionHelper: "Protege backups e arquivos financeiros em dispositivos compartilhados.",
    timeout: "Encerrar sessão por inatividade",
    sessionsTitle: "Sessões ativas",
    sessionsDescription: "Dispositivos que acessaram sua conta recentemente.",
    currentSession: "Sessão atual",
    revoke: "Encerrar sessão",
    revokeOthers: "Encerrar outras sessões",
    twoFactorEnabled: "Verificação em duas etapas ativada.",
    twoFactorDisabled: "Verificação em duas etapas desativada.",
    passwordChanged: "Senha atualizada nesta sessão demonstrativa.",
    invalidPassword: "Confira os campos. A nova senha precisa ter pelo menos 8 caracteres e coincidir.",
  },
  activity: {
    title: "Histórico de atividades",
    description: "Acompanhe mudanças importantes realizadas na sua conta e nos espaços financeiros.",
    search: "Buscar atividade",
    allTypes: "Todos os tipos",
    allStatuses: "Todos os estados",
    export: "Exportar histórico",
    empty: "Nenhuma atividade encontrada com esses filtros.",
    types: {
      login: "Acesso",
      security: "Segurança",
      profile: "Perfil",
      workspace: "Espaço",
      data: "Dados",
      backup: "Backup",
    },
    statuses: {
      success: "Concluído",
      attention: "Atenção",
      blocked: "Bloqueado",
    },
    actor: "Responsável",
    device: "Dispositivo",
  },
  backups: {
    title: "Backups e recuperação",
    description: "Gere cópias completas e restaure seus dados quando necessário.",
    create: "Criar backup agora",
    automaticTitle: "Backup automático",
    automatic: "Manter cópias automáticas",
    automaticHelper: "Gera uma cópia periódica com os dados financeiros e configurações.",
    frequency: "Frequência",
    daily: "Diariamente",
    weekly: "Semanalmente",
    monthly: "Mensalmente",
    retention: "Quantidade de cópias mantidas",
    attachments: "Incluir comprovantes e anexos",
    attachmentsHelper: "Pode aumentar o tamanho final do arquivo.",
    snapshotsTitle: "Cópias disponíveis",
    download: "Baixar",
    restore: "Restaurar",
    remove: "Excluir",
    automaticBadge: "Automático",
    manualBadge: "Manual",
    available: "Disponível",
    processing: "Processando",
    failed: "Falhou",
    restoreTitle: "Restaurar um backup",
    restoreDescription: "Selecione um arquivo JSON gerado pela dashboard. A prévia é validada antes de qualquer substituição.",
    selectFile: "Selecionar arquivo",
    validFile: "Backup válido e pronto para restauração.",
    invalidFile: "O arquivo não possui a estrutura de backup esperada.",
    confirmRestore: "Confirmar restauração",
    created: "Backup criado e baixado com sucesso.",
    restored: "Backup validado. A restauração definitiva será persistida na integração da Fase 15.",
    removed: "Backup removido da lista.",
    dangerTitle: "Controle dos dados",
    exportAll: "Exportar todos os dados",
    exportAllHelper: "Baixe uma cópia completa em JSON para manter fora da plataforma.",
    deleteAccount: "Solicitar exclusão da conta",
    deleteAccountHelper: "A exclusão definitiva exigirá confirmação segura no backend.",
    deleteConfirmation: "Digite EXCLUIR para confirmar a solicitação demonstrativa.",
    deleteRequested: "Solicitação de exclusão registrada nesta demonstração.",
  },
  feedback: {
    profileSaved: "Perfil atualizado.",
    preferencesSaved: "Preferências financeiras atualizadas.",
    notificationsSaved: "Notificações atualizadas.",
    securitySaved: "Configurações de segurança atualizadas.",
    sessionRevoked: "Sessão encerrada.",
    otherSessionsRevoked: "Outras sessões foram encerradas.",
    backupSettingsSaved: "Preferências de backup atualizadas.",
  },
  accessibility: {
    settingsNavigation: "Seções de configurações",
    summary: "Resumo das configurações",
  },
} as const;
