import type {
  PayableRecurrence,
  PayableStatus,
  PayableValueType,
} from "@/types/contas-a-pagar";

export const payablesContent = {
  heading: {
    eyebrow: "Compromissos financeiros",
    title: "Contas a pagar",
    description:
      "Organize vencimentos, recorrências e pagamentos para saber exatamente o que ainda compromete o seu mês.",
    newAction: "Nova conta",
  },
  summary: {
    pending: "Total pendente",
    pendingHelper: "Saldo ainda não quitado",
    today: "Vence hoje",
    todayHelper: "Contas com vencimento nesta data",
    sevenDays: "Próximos 7 dias",
    sevenDaysHelper: "Compromissos que exigem atenção",
    overdue: "Em atraso",
    overdueHelper: "Valores vencidos e não pagos",
    paid: "Pago no mês",
    paidHelper: "Total confirmado em julho",
  },
  filters: {
    searchPlaceholder: "Buscar conta, categoria ou observação",
    allStatuses: "Todos os status",
    allPeriods: "Todos os períodos",
    allCategories: "Todas as categorias",
    allAccounts: "Todas as contas",
    clear: "Limpar filtros",
    periods: {
      today: "Vence hoje",
      sevenDays: "Próximos 7 dias",
      month: "Neste mês",
      overdue: "Atrasadas",
    },
  },
  list: {
    kicker: "Agenda de pagamentos",
    title: "Compromissos cadastrados",
    countSuffix: "contas encontradas",
    columns: {
      description: "Conta",
      dueDate: "Vencimento",
      category: "Categoria",
      account: "Conta de pagamento",
      status: "Status",
      remaining: "Saldo restante",
      actions: "Ações",
    },
    payAction: "Registrar pagamento",
    paidAction: "Quitada",
    remaining: "Restante",
    paidAmount: "Já pago",
    recurring: "Recorrente",
    emptyTitle: "Nenhuma conta encontrada",
    emptyDescription:
      "Ajuste os filtros ou cadastre um novo compromisso financeiro.",
  },
  insight: {
    kicker: "Visão do período",
    title: "Pressão financeira",
    description:
      "Entenda quanto dos próximos dias já está comprometido e quais contas exigem prioridade.",
    committedThisMonth: "Comprometido neste mês",
    fixedExpenses: "Despesas fixas",
    variableExpenses: "Despesas variáveis",
    nextDue: "Próximo vencimento",
    attentionTitle: "Atenção necessária",
    attentionDescription:
      "Priorize contas atrasadas e vencimentos próximos antes de assumir novos compromissos.",
  },
  newDialog: {
    eyebrow: "Novo compromisso",
    title: "Adicionar conta a pagar",
    description:
      "Cadastre uma obrigação futura e deixe o planejamento mensal mais previsível.",
    closeAriaLabel: "Fechar cadastro de conta a pagar",
    fields: {
      description: "Descrição",
      descriptionPlaceholder: "Ex.: Conta de água",
      category: "Categoria",
      amount: "Valor",
      dueDate: "Data de vencimento",
      account: "Conta de pagamento",
      recurrence: "Recorrência",
      valueType: "Tipo de valor",
      notes: "Observações",
      notesPlaceholder: "Informações opcionais sobre este compromisso",
    },
    cancel: "Cancelar",
    submit: "Salvar conta",
    success: "Conta a pagar adicionada com sucesso.",
  },
  paymentDialog: {
    eyebrow: "Baixa de pagamento",
    title: "Registrar pagamento",
    description:
      "Informe o valor pago. Pagamentos parciais mantêm o saldo restante em aberto.",
    closeAriaLabel: "Fechar registro de pagamento",
    total: "Valor total",
    alreadyPaid: "Já pago",
    remaining: "Saldo restante",
    fields: {
      amount: "Valor pago agora",
      date: "Data do pagamento",
      account: "Conta utilizada",
    },
    cancel: "Cancelar",
    submit: "Confirmar pagamento",
    successFull: "Conta marcada como paga.",
    successPartial: "Pagamento parcial registrado.",
  },
  statuses: {
    pending: "Pendente",
    overdue: "Atrasada",
    partial: "Parcial",
    paid: "Paga",
  } satisfies Record<PayableStatus, string>,
  recurrences: {
    none: "Sem recorrência",
    weekly: "Semanal",
    monthly: "Mensal",
    yearly: "Anual",
  } satisfies Record<PayableRecurrence, string>,
  valueTypes: {
    fixed: "Valor fixo",
    variable: "Valor variável",
  } satisfies Record<PayableValueType, string>,
  categories: [
    "Moradia",
    "Alimentação",
    "Transporte",
    "Saúde",
    "Educação",
    "Assinaturas",
    "Impostos pessoais",
    "Dívidas",
    "Outros",
  ],
  validation: {
    required: "Preencha os campos obrigatórios.",
    positiveAmount: "Informe um valor maior que zero.",
    paymentLimit: "O pagamento não pode ser maior que o saldo restante.",
  },
} as const;
