import type {
  AccountFilter,
  AccountGroup,
  AccountMovementType,
  AccountType,
} from "@/types/contas";

export const accountsContent = {
  heading: {
    eyebrow: "Organização financeira",
    title: "Contas e carteiras",
    description:
      "Acompanhe onde seu dinheiro está, transfira valores e mantenha o saldo de cada conta organizado.",
    transferAction: "Transferir entre contas",
    newAccountAction: "Nova conta",
  },
  summary: {
    totalBalance: "Saldo total",
    totalBalanceHelper: "Soma das contas incluídas no patrimônio",
    projectedBalance: "Saldo projetado",
    projectedBalanceHelper: "Após compromissos financeiros pendentes",
    availableBalance: "Disponível para uso",
    availableBalanceHelper: "Saldo total sem valores reservados",
    reservedBalance: "Valor reservado",
    reservedBalanceHelper: "Protegido para metas e emergências",
    activeAccounts: "Contas ativas",
    activeAccountsHelper: "Contas e carteiras cadastradas",
    projectionLabel: "Previsão após compromissos",
    distributionLabel: "Distribuição atual do patrimônio",
  },
  filters: {
    searchPlaceholder: "Buscar conta ou instituição",
    searchAriaLabel: "Buscar contas",
    labels: {
      all: "Todas",
      bank: "Bancárias",
      wallet: "Carteiras",
      reserve: "Reservas",
    } satisfies Record<AccountFilter, string>,
  },
  accounts: {
    kicker: "Seu dinheiro",
    title: "Contas cadastradas",
    countSuffix: "contas encontradas",
    balance: "Saldo atual",
    projected: "Saldo projetado",
    primary: "Principal",
    included: "Incluída no patrimônio",
    excluded: "Fora do patrimônio",
    viewMovements: "Ver movimentações",
    selected: "Conta selecionada",
    emptyTitle: "Nenhuma conta encontrada",
    emptyDescription: "Ajuste a busca ou cadastre uma nova conta financeira.",
  },
  movements: {
    kicker: "Histórico recente",
    title: "Movimentações da conta",
    allAccountsTitle: "Movimentações recentes",
    emptyTitle: "Nenhuma movimentação nesta conta",
    emptyDescription: "As próximas entradas, saídas e transferências aparecerão aqui.",
    transferTo: "Transferência para",
    transferFrom: "Transferência recebida de",
    types: {
      income: "Entrada",
      expense: "Saída",
      transfer: "Transferência",
    } satisfies Record<AccountMovementType, string>,
  },
  distribution: {
    kicker: "Composição financeira",
    title: "Distribuição do saldo",
    description:
      "Veja a participação de cada conta no total do seu patrimônio financeiro atual.",
    total: "Total considerado",
  },
  accountTypes: {
    checking: "Conta corrente",
    digital: "Conta digital",
    savings: "Poupança ou reserva",
    cash: "Dinheiro em espécie",
    investment: "Conta de investimento",
  } satisfies Record<AccountType, string>,
  accountGroups: {
    bank: "Conta bancária",
    wallet: "Carteira",
    reserve: "Reserva",
  } satisfies Record<AccountGroup, string>,
  newAccountDialog: {
    eyebrow: "Nova origem financeira",
    title: "Adicionar conta",
    description:
      "Cadastre uma conta bancária, carteira, reserva ou outra origem onde você mantém dinheiro.",
    closeAriaLabel: "Fechar cadastro de conta",
    fields: {
      name: "Nome da conta",
      namePlaceholder: "Ex.: Conta do dia a dia",
      institution: "Instituição ou identificação",
      institutionPlaceholder: "Ex.: Banco, carteira ou local",
      type: "Tipo de conta",
      initialBalance: "Saldo inicial",
      includeInTotal: "Incluir esta conta no patrimônio total",
    },
    cancel: "Cancelar",
    submit: "Salvar conta",
    success: "Conta adicionada com sucesso.",
  },
  transferDialog: {
    eyebrow: "Movimentação interna",
    title: "Transferir entre contas",
    description:
      "Mova dinheiro entre suas próprias contas sem registrar uma nova receita ou despesa.",
    closeAriaLabel: "Fechar transferência",
    fields: {
      source: "Conta de origem",
      destination: "Conta de destino",
      amount: "Valor da transferência",
      date: "Data",
      description: "Descrição",
      descriptionPlaceholder: "Ex.: Reforço da reserva",
    },
    sourceBalance: "Saldo disponível na origem",
    cancel: "Cancelar",
    submit: "Confirmar transferência",
    success: "Transferência realizada com sucesso.",
  },
  validation: {
    required: "Preencha os campos obrigatórios.",
    positiveAmount: "Informe um valor maior que zero.",
    differentAccounts: "Escolha contas diferentes para a transferência.",
    insufficientBalance: "O saldo da conta de origem é insuficiente.",
    duplicateName: "Já existe uma conta com esse nome.",
  },
} as const;
