import type {
  DataToolsView,
  ExportDataset,
  ImportRowStatus,
  ImportSourceType,
  RuleField,
  RuleOperator,
} from "@/types/dados-e-automacoes";

export const dataToolsContent = {
  heading: {
    eyebrow: "Organização dos dados",
    title: "Importação, exportação e regras",
    description:
      "Traga extratos para a dashboard, mantenha cópias dos seus dados e automatize a categorização dos lançamentos.",
    sample: "Usar arquivo de exemplo",
    backup: "Gerar backup completo",
  },
  views: {
    import: "Importar",
    export: "Exportar",
    rules: "Regras automáticas",
    history: "Histórico",
  } satisfies Record<DataToolsView, string>,
  summary: {
    previewRows: "Linhas aguardando revisão",
    activeRules: "Regras automáticas ativas",
    lastImport: "Última importação",
    datasets: "Conjuntos exportáveis",
    noImport: "Nenhuma importação concluída",
    rulesHelper: "Aplicadas antes da confirmação",
    datasetsHelper: "Além do backup completo",
    datasetCount: "9",
  },
  import: {
    title: "Importar extrato ou planilha",
    description:
      "Use arquivos CSV de planilhas ou OFX exportados pelo banco. Os dados são revisados antes de entrar na organização financeira.",
    dropTitle: "Arraste o arquivo para esta área",
    dropHelper: "ou selecione um arquivo no computador",
    chooseFile: "Selecionar arquivo",
    accepted: "Formatos aceitos: CSV e OFX",
    privacy: "Nesta fase demonstrativa, o processamento acontece no navegador e não envia o arquivo para serviços externos.",
    reading: "Lendo arquivo...",
    invalidFile: "Não foi possível ler o arquivo. Verifique se ele está em CSV ou OFX.",
    emptyFile: "O arquivo não possui movimentações reconhecíveis.",
    mappingTitle: "Correspondência das colunas",
    mappingDescription: "Confirme o significado de cada coluna encontrada no CSV.",
    mappingIgnore: "Ignorar coluna",
    mappingDate: "Data",
    mappingDescriptionField: "Descrição",
    mappingAmount: "Valor",
    mappingType: "Tipo",
    mappingCategory: "Categoria",
    mappingAccount: "Conta",
    sourceFile: "Arquivo selecionado",
    detectedRows: "movimentações detectadas",
    clear: "Remover arquivo",
    sampleFileName: "extrato-exemplo-julho-2026.csv",
    sampleCsv: "Data;Descrição;Valor;Tipo;Categoria;Conta\n25/07/2026;Mercado do bairro;-186,40;Despesa;Alimentação;Nubank\n24/07/2026;PIX recebido - Projeto digital;1450,00;Receita;Serviços;Banco Inter\n23/07/2026;UBER TRIP;-34,90;Despesa;;Nubank\n22/07/2026;NETFLIX.COM;-44,90;Despesa;;Conta principal\n21/07/2026;Farmácia Central;-82,50;Despesa;Saúde;Conta principal",
  },
  preview: {
    title: "Prévia da importação",
    description: "Revise as movimentações, corrija o necessário e escolha quais linhas serão importadas.",
    selected: "Selecionadas",
    ready: "Prontas",
    review: "Revisar",
    duplicate: "Possíveis duplicadas",
    selectAll: "Selecionar todas",
    clearSelection: "Limpar seleção",
    importSelected: "Importar selecionadas",
    noRows: "Selecione um arquivo para visualizar as movimentações.",
    date: "Data",
    descriptionField: "Descrição",
    category: "Categoria",
    account: "Conta",
    type: "Tipo",
    amount: "Valor",
    status: "Situação",
    editHint: "Os campos podem ser ajustados diretamente na prévia.",
    income: "Receita",
    expense: "Despesa",
    transfer: "Transferência",
    issues: {
      missingDate: "Data não reconhecida",
      missingDescription: "Descrição ausente",
      zeroAmount: "Valor zerado",
      duplicate: "Movimentação semelhante já cadastrada",
    },
    statusLabels: {
      ready: "Pronta",
      review: "Revisar",
      duplicate: "Duplicada",
    } satisfies Record<ImportRowStatus, string>,
  },
  export: {
    title: "Exportação avançada",
    description:
      "Escolha o conjunto de dados, o período e o formato para criar uma cópia organizada das suas informações.",
    dataset: "Dados para exportar",
    format: "Formato",
    separator: "Separador do CSV",
    period: "Período",
    startDate: "Data inicial",
    endDate: "Data final",
    includeHeaders: "Incluir nomes das colunas",
    exportNow: "Exportar agora",
    previewTitle: "Resumo da exportação",
    estimatedRows: "Registros disponíveis",
    fullBackupModules: "9 módulos",
    fileName: "Nome estimado do arquivo",
    csv: "CSV para planilhas",
    json: "JSON estruturado",
    semicolon: "Ponto e vírgula (;)",
    comma: "Vírgula (,)",
    noPeriod: "O conjunto selecionado não possui filtro por data.",
    backupNote:
      "O backup completo reúne os dados demonstrativos de todos os módulos em um único arquivo JSON.",
    datasets: {
      transactions: "Lançamentos",
      accounts: "Contas e carteiras",
      cards: "Cartões e faturas",
      payables: "Contas a pagar",
      receivables: "Recebimentos",
      budgets: "Categorias e orçamentos",
      goals: "Metas e reservas",
      debts: "Dívidas e pagamentos",
      subscriptions: "Assinaturas e cobranças",
      "full-backup": "Backup completo",
    } satisfies Record<ExportDataset, string>,
    headers: {
      transactions: ["Identificador", "Data", "Descrição", "Categoria", "Conta", "Conta de destino", "Forma de pagamento", "Tipo", "Situação", "Valor", "Observação"],
      accounts: ["Identificador", "Nome", "Instituição", "Tipo", "Grupo", "Saldo atual", "Saldo projetado", "Conta principal", "Incluída no total", "Criada em"],
      cards: ["Registro", "Identificador", "Cartão", "Instituição", "Referência", "Data", "Situação", "Valor", "Detalhe"],
      payables: ["Identificador", "Vencimento", "Descrição", "Categoria", "Conta", "Situação", "Recorrência", "Valor", "Valor pago", "Observação"],
      receivables: ["Identificador", "Data prevista", "Descrição", "Origem", "Pagador", "Categoria", "Conta", "Situação", "Recorrência", "Valor", "Valor recebido", "Observação"],
      budgets: ["Registro", "Identificador", "Nome", "Tipo", "Mês", "Limite", "Alerta", "Ativo", "Descrição"],
      goals: ["Registro", "Identificador", "Meta", "Tipo", "Categoria", "Conta", "Data", "Situação", "Valor alvo", "Valor atual", "Aporte mensal", "Observação"],
      debts: ["Registro", "Identificador", "Dívida", "Credor", "Tipo", "Conta", "Data", "Situação", "Valor original", "Saldo atual", "Juros", "Parcela", "Observação"],
      subscriptions: ["Registro", "Identificador", "Serviço", "Fornecedor", "Categoria", "Conta", "Data", "Situação", "Periodicidade", "Valor", "Observação"],
    },
  },
  rules: {
    title: "Regras automáticas",
    description:
      "Crie condições para preencher categoria, conta ou tipo sempre que uma movimentação compatível for importada.",
    newRule: "Nova regra",
    active: "Ativa",
    paused: "Pausada",
    matches: "correspondências nos dados atuais",
    edit: "Editar",
    pause: "Pausar",
    resume: "Ativar",
    remove: "Excluir",
    moveUp: "Aumentar prioridade",
    moveDown: "Diminuir prioridade",
    test: "Testar regras",
    noRules: "Nenhuma regra encontrada.",
    condition: "Condição",
    action: "Ações aplicadas",
    priority: "Prioridade",
    testTitle: "Resultado do teste",
    testDescription: "Exemplos de movimentações reconhecidas pelas regras ativas.",
    noMatches: "Nenhuma correspondência encontrada nos dados atuais.",
    fields: {
      description: "Descrição",
      category: "Categoria atual",
      account: "Conta atual",
    } satisfies Record<RuleField, string>,
    operators: {
      contains: "contém",
      "starts-with": "começa com",
      equals: "é igual a",
    } satisfies Record<RuleOperator, string>,
    actions: {
      category: "Definir categoria",
      account: "Definir conta",
      type: "Definir tipo",
    },
  },
  ruleDialog: {
    eyebrow: "Automação pessoal",
    createTitle: "Criar regra automática",
    editTitle: "Editar regra automática",
    description: "A primeira regra ativa compatível será aplicada à movimentação importada.",
    name: "Nome da regra",
    namePlaceholder: "Ex.: Categorizar transporte por aplicativo",
    field: "Campo analisado",
    operator: "Comparação",
    value: "Texto procurado",
    valuePlaceholder: "Ex.: UBER",
    actionsTitle: "Preenchimento automático",
    category: "Categoria",
    account: "Conta",
    type: "Tipo",
    keepCurrent: "Manter valor atual",
    active: "Ativar esta regra",
    cancel: "Cancelar",
    create: "Criar regra",
    save: "Salvar alterações",
    required: "Preencha o nome, a condição e pelo menos uma ação.",
  },
  history: {
    title: "Histórico de importações",
    description: "Acompanhe os arquivos processados e o resultado de cada importação.",
    file: "Arquivo",
    date: "Processado em",
    imported: "Importadas",
    ignored: "Ignoradas",
    duplicates: "Duplicadas",
    status: "Situação",
    completed: "Concluída",
    partial: "Concluída com revisão",
    empty: "Nenhuma importação registrada.",
  },
  sourceTypes: {
    csv: "CSV",
    ofx: "OFX",
  } satisfies Record<ImportSourceType, string>,
  feedback: {
    imported: "Movimentações importadas para esta sessão.",
    noSelection: "Selecione pelo menos uma movimentação válida.",
    exported: "Arquivo gerado com sucesso.",
    ruleCreated: "Regra automática criada.",
    ruleUpdated: "Regra automática atualizada.",
    ruleRemoved: "Regra removida.",
    rulesTested: "Teste das regras concluído.",
  },
  accessibility: {
    views: "Alternar ferramentas de dados",
    summary: "Resumo das ferramentas de dados",
    upload: "Área para selecionar arquivo financeiro",
    closeDialog: "Fechar formulário da regra",
  },
} as const;
