import type { DebtPriority, DebtStatus, DebtType } from "@/types/dividas";

export const debtsContent = {
  heading: {
    eyebrow: "Planejamento financeiro",
    title: "Dívidas e parcelamentos",
    description:
      "Acompanhe empréstimos, financiamentos e acordos em um único lugar, com clareza sobre juros, parcelas e prazo de quitação.",
    newPayment: "Registrar pagamento",
    newDebt: "Nova dívida",
  },
  summary: {
    outstanding: "Saldo devedor",
    outstandingHelper: "Total ainda necessário para quitar",
    monthly: "Compromisso mensal",
    monthlyHelper: "Parcelas previstas por mês",
    overdue: "Valor em atraso",
    overdueHelper: "Compromissos que exigem atenção",
    interest: "Juros restantes estimados",
    interestHelper: "Estimativa sobre as parcelas atuais",
    debtFree: "Previsão de quitação",
    debtFreeHelper: "Mantendo o plano atual",
    activeSingular: "compromisso ativo",
    activePlural: "compromissos ativos",
    incomeReference: "da renda de referência",
    attention: "Atenção",
  },
  toolbar: {
    debts: "Dívidas",
    payments: "Histórico de pagamentos",
    searchPlaceholder: "Buscar dívida, credor ou observação",
    allTypes: "Todos os tipos",
    allStatuses: "Todos os status",
    allPriorities: "Todas as prioridades",
    clear: "Limpar filtros",
    typeLabel: "Tipo",
    statusLabel: "Status",
    priorityLabel: "Prioridade",
  },
  list: {
    eyebrow: "Compromissos cadastrados",
    title: "Plano de quitação",
    resultSingular: "dívida encontrada",
    resultPlural: "dívidas encontradas",
    original: "Valor original",
    balance: "Saldo atual",
    installment: "Parcela mensal",
    nextDue: "Próximo vencimento",
    creditor: "Credor",
    interest: "Juros ao ano",
    installments: "Parcelas",
    account: "Conta de pagamento",
    remaining: "restantes",
    paid: "pagas",
    pay: "Registrar pagamento",
    edit: "Editar",
    settle: "Quitar dívida",
    emptyTitle: "Nenhuma dívida encontrada",
    emptyDescription: "Ajuste os filtros ou cadastre um novo compromisso financeiro.",
    originalPrefix: "de",
    unknownAccount: "Conta não informada",
  },
  details: {
    eyebrow: "Detalhes da dívida",
    title: "Acompanhamento do contrato",
    noSelection: "Selecione uma dívida para visualizar os detalhes.",
    progressSuffix: "do valor principal quitado",
    progress: "Progresso da quitação",
    paidPrincipal: "Principal já quitado",
    remainingInterest: "Juros restantes estimados",
    startDate: "Início do contrato",
    nextDue: "Próximo vencimento",
    timeline: "Linha de parcelas",
    completedInstallment: "Paga",
    nextInstallment: "Próxima",
    overdueInstallment: "Atrasada",
    futureInstallment: "Futura",
    moreInstallments: "parcelas adicionais não exibidas",
  },
  simulator: {
    eyebrow: "Simulação de antecipação",
    title: "Quanto você economiza pagando mais?",
    description: "A simulação é aproximada e usa o saldo, os juros e a parcela cadastrados.",
    selectDebt: "Dívida simulada",
    extraPayment: "Valor extra por mês",
    currentPlan: "Plano atual",
    newPlan: "Novo plano",
    months: "meses",
    monthsSaved: "Meses antecipados",
    interestSaved: "Juros economizados",
    newMonthly: "Novo pagamento mensal",
    noSavings: "Aumente o valor extra para visualizar uma redução no prazo.",
  },
  strategy: {
    eyebrow: "Estratégia de quitação",
    title: "Ordem recomendada",
    avalanche: "Avalanche",
    snowball: "Bola de neve",
    avalancheDescription: "Prioriza as maiores taxas de juros para reduzir o custo total.",
    snowballDescription: "Prioriza os menores saldos para gerar conquistas mais rápidas.",
    firstPriority: "Prioridade atual",
    annualRate: "ao ano",
    currentBalance: "saldo",
  },
  payments: {
    eyebrow: "Movimentações realizadas",
    title: "Histórico de pagamentos",
    resultSingular: "pagamento registrado",
    resultPlural: "pagamentos registrados",
    date: "Data",
    debt: "Dívida",
    account: "Conta utilizada",
    principal: "Valor amortizado",
    interest: "Juros",
    amount: "Total pago",
    emptyTitle: "Nenhum pagamento encontrado",
    emptyDescription: "Os pagamentos registrados aparecerão aqui com a separação entre principal e juros.",
    removedDebt: "Dívida removida",
  },
  debtDialog: {
    createTitle: "Cadastrar nova dívida",
    createDescription: "Adicione as condições do compromisso para acompanhar a quitação.",
    editTitle: "Editar dívida",
    editDescription: "Atualize valores, parcelas, datas ou condições do contrato.",
    name: "Nome da dívida",
    creditor: "Credor ou instituição",
    type: "Tipo de compromisso",
    originalAmount: "Valor original",
    currentBalance: "Saldo devedor atual",
    annualInterestRate: "Taxa de juros ao ano",
    totalInstallments: "Total de parcelas",
    paidInstallments: "Parcelas já pagas",
    installmentAmount: "Valor da parcela",
    nextDueDate: "Próximo vencimento",
    startDate: "Data de início",
    account: "Conta de pagamento",
    priority: "Prioridade",
    status: "Status",
    notes: "Observações",
    notesPlaceholder: "Ex.: contrato renegociado, desconto para antecipação ou condição especial.",
    cancel: "Cancelar",
    create: "Cadastrar dívida",
    save: "Salvar alterações",
    requiredError: "Preencha os campos obrigatórios para continuar.",
    valuesError: "Informe valores e quantidade de parcelas válidos.",
    installmentsError: "As parcelas pagas não podem superar o total contratado.",
    successCreate: "Dívida cadastrada com sucesso.",
    successEdit: "Dívida atualizada com sucesso.",
  },
  paymentDialog: {
    title: "Registrar pagamento",
    description: "O sistema separa uma estimativa de juros e amortização do saldo.",
    debt: "Dívida",
    date: "Data do pagamento",
    amount: "Valor pago",
    account: "Conta utilizada",
    note: "Observação",
    notePlaceholder: "Ex.: parcela mensal, pagamento antecipado ou quitação.",
    scheduledAmount: "Parcela prevista",
    currentBalance: "Saldo atual",
    estimatedInterest: "Juros estimados neste pagamento",
    estimatedPrincipal: "Amortização estimada",
    cancel: "Cancelar",
    confirm: "Confirmar pagamento",
    requiredError: "Selecione a dívida, a conta e informe o pagamento.",
    amountError: "O pagamento deve ser maior que zero e não pode ultrapassar a quitação estimada.",
    success: "Pagamento registrado e saldo atualizado.",
    defaultNote: "Parcela mensal",
    settlementNote: "Quitação antecipada",
    settled: "Pagamento registrado. A dívida foi quitada.",
  },
  feedback: {
    settled: "Dívida quitada com sucesso.",
  },
  accessibility: {
    debtActions: "Ações da dívida",
    closeDialog: "Fechar janela",
    summary: "Resumo das dívidas",
    viewTabs: "Visualização das dívidas",
    search: "Buscar dívidas",
  },
  types: {
    "personal-loan": "Empréstimo pessoal",
    financing: "Financiamento",
    "credit-card-installment": "Parcelamento de fatura",
    "family-debt": "Dívida pessoal ou familiar",
    overdraft: "Cheque especial",
    other: "Outro compromisso",
  } satisfies Record<DebtType, string>,
  statuses: {
    active: "Em dia",
    overdue: "Em atraso",
    paid: "Quitada",
    renegotiated: "Renegociada",
  } satisfies Record<DebtStatus, string>,
  priorities: {
    high: "Alta prioridade",
    medium: "Média prioridade",
    low: "Baixa prioridade",
  } satisfies Record<DebtPriority, string>,
} as const;
