export const financialIntelligenceContent = {
  sources: {
    "manual-payable": "Conta cadastrada",
    "card-invoice": "Fatura de cartão",
    subscription: "Assinatura recorrente",
    "debt-installment": "Parcela de dívida",
  },
  recurring: {
    recurring: "Recorrente",
    oneTime: "Avulsa",
    automatic: "Sincronizada automaticamente",
    explanation: "A recorrência serve apenas para identificar que essa conta costuma se repetir. Ela não cria contas futuras nem copia o valor: cadastre cada nova cobrança com o valor real quando ela chegar.",
  },
  accounting: {
    accountNotProvided: "Conta não informada",
    cardInvoiceCategory: "Fatura de cartão",
    cardInvoiceTitle: "Fatura",
    genericCardInvoiceTitle: "Fatura de cartão",
    subscriptionCategory: "Assinatura",
    subscriptionFallback: "Assinatura",
    debtInstallmentCategory: "Parcela de dívida",
    debtInstallmentTitle: "Parcela",
    commitmentPaymentNote: "Pagamento registrado em Contas a pagar",
    commitmentPaymentMethod: "Pagamento de compromisso",
    commitmentPaymentTitle: "Pagamento",
    receiptPaymentMethod: "Recebimento",
    receiptPaymentTitle: "Recebimento",
    subscriptionPaymentMethod: "Cobrança recorrente",
    subscriptionPaymentTitle: "Assinatura",
    debtsCategory: "Dívidas",
    debtPaymentMethod: "Pagamento de dívida",
    debtPaymentTitle: "Pagamento de dívida",
    calendarPaymentNote: "Pagamento concluído pelo calendário",
  },
  search: {
    cardsLabel: "Buscar cartões, faturas, compras ou parcelamentos",
    cardsPlaceholder: "Buscar cartão, fatura, compra, categoria ou valor",
  },
  calendar: {
    searchLabel: "Buscar compromissos no calendário",
    searchPlaceholder: "Buscar conta, fatura, assinatura, categoria ou valor",
  },
  debts: {
    automatic: "Dívida identificada automaticamente",
    editBlocked: "Este registro é sincronizado com a origem e deve ser alterado na página correspondente.",
  },
  feedback: {
    paymentSaved: "Pagamento salvo e refletido em toda a dashboard.",
    receiptSaved: "Recebimento salvo e refletido em toda a dashboard.",
    transactionSaved: "Lançamento salvo e refletido nas contas.",
    transactionRemoved: "Lançamento removido e saldo recalculado.",
    automaticTransactionProtected: "Este lançamento é sincronizado. Faça a alteração na conta, fatura, assinatura, dívida ou recebimento de origem.",
  },
} as const;
