export const integrationContent = {
  loading: "Conectando à sua base financeira...",
  backendUnavailable: "Não foi possível conectar ao backend local. Confirme se o NestJS está rodando na porta 3001.",
  sessionExpired: "Sua sessão expirou. Entre novamente.",
  unexpectedError: "Não foi possível concluir a operação.",
  authenticationError: "Não foi possível validar a autenticação.",
  workspaceLoadError: "Não foi possível carregar os espaços financeiros.",
  inviteCopied: "Convite criado e link copiado para a área de transferência.",
  inviteCreated: "Convite criado. Copie o link retornado pela API.",
  localRecoveryToken: "Token local de recuperação",
  login: {
    submitting: "Entrando...",
    backendNote: "Backend local NestJS conectado ao PostgreSQL.",
  },
  register: {
    submitting: "Criando conta...",
  },
  recovery: {
    preparing: "Preparando...",
    resetNow: "Redefinir senha agora",
  },
  resetPassword: {
    eyebrow: "SEGURANÇA LOCAL",
    title: "Redefinir senha",
    description: "Use o token gerado pelo backend local.",
    token: "Token de recuperação",
    password: "Nova senha",
    confirmation: "Confirmar nova senha",
    validation: "Informe o token local e uma senha com pelo menos 8 caracteres.",
    mismatch: "As senhas não são iguais.",
    failure: "Não foi possível alterar a senha.",
    submit: "Salvar nova senha",
    submitting: "Salvando...",
    back: "Voltar para o login",
    successTitle: "Senha atualizada",
    successDescription: "As sessões anteriores foram encerradas por segurança.",
    successAction: "Entrar com a nova senha",
  },
  invitation: {
    loading: "Carregando convite...",
    accepting: "Aceitando...",
    emailRestrictionPrefix: "O convite só pode ser aceito por",
  },
  accountMenu: {
    protectedSession: "Sessão protegida pelo backend local",
    leaving: "Saindo...",
  },
  footerDatabase: "PostgreSQL local",
} as const;
