export const goalsContent = {
  accessibility: {
    summary: "Resumo das metas financeiras",
    closeDialog: "Fechar formulário",
    goalActions: "Ações da meta",
  },
  heading: {
    eyebrow: "Planejamento pessoal",
    title: "Metas e reservas",
    description:
      "Transforme objetivos em planos claros, acompanhe aportes e preserve valores que não devem ser usados no cotidiano.",
    newGoal: "Nova meta",
    newContribution: "Adicionar valor",
  },
  summary: {
    target: "Objetivos planejados",
    targetHint: "Soma dos valores-alvo",
    saved: "Valor acumulado",
    savedHint: "Separado entre metas e reservas",
    remaining: "Ainda necessário",
    remainingHint: "Para concluir todos os objetivos",
    monthly: "Aportes mensais",
    monthlyHint: "Planejamento recorrente atual",
  },
  toolbar: {
    searchLabel: "Buscar",
    searchPlaceholder: "Buscar meta ou descrição",
    typeLabel: "Organização",
    statusLabel: "Status",
    allTypes: "Todas",
    reserves: "Reservas",
    goals: "Objetivos",
    allStatuses: "Todos os status",
    clear: "Limpar filtros",
    goalsView: "Metas",
    movementsView: "Movimentações",
  },
  list: {
    eyebrow: "Objetivos financeiros",
    title: "Seu planejamento",
    count: "itens organizados",
    current: "Acumulado",
    target: "Meta",
    remaining: "Falta",
    monthly: "Aporte mensal",
    targetDate: "Prazo",
    requiredMonthly: "Necessário por mês",
    account: "Conta vinculada",
    priority: "Prioridade",
    reserve: "Reserva",
    goal: "Objetivo",
    addValue: "Adicionar valor",
    edit: "Editar meta",
    pause: "Pausar",
    resume: "Retomar",
    complete: "Marcar como concluída",
    emptyTitle: "Nenhuma meta encontrada",
    emptyDescription:
      "Ajuste os filtros ou crie um novo objetivo para começar seu planejamento.",
  },
  statuses: {
    "on-track": "No ritmo",
    attention: "Requer atenção",
    completed: "Concluída",
    paused: "Pausada",
  },
  priorities: {
    high: "Alta",
    medium: "Média",
    low: "Baixa",
  },
  categories: {
    emergency: "Emergência",
    travel: "Viagem",
    purchase: "Compra planejada",
    home: "Casa",
    education: "Educação",
    debt: "Quitação de dívida",
    other: "Outro objetivo",
  },
  insight: {
    eyebrow: "Proteção financeira",
    title: "Reserva de emergência",
    description:
      "Acompanhe quantos meses de despesas essenciais já estão protegidos pela sua reserva.",
    current: "Valor reservado",
    essentialCost: "Custo essencial mensal",
    coveredMonths: "Meses protegidos",
    targetMonths: "Meta de proteção",
    target: "Meta financeira",
    healthyTitle: "Proteção em construção",
    healthyDescription:
      "Continue com os aportes mensais para ampliar sua segurança sem comprometer o orçamento.",
    attentionTitle: "Priorize sua proteção",
    attentionDescription:
      "Sua cobertura ainda está abaixo de um mês. Considere priorizar esta reserva nos próximos aportes.",
  },
  plan: {
    title: "Plano mensal",
    description: "Distribuição dos aportes planejados entre os objetivos ativos.",
    total: "Total planejado",
    activeGoals: "metas ativas",
    noPlan: "Nenhum aporte mensal configurado.",
  },
  movements: {
    eyebrow: "Histórico",
    title: "Movimentações das metas",
    description:
      "Aportes e retiradas registrados nos objetivos financeiros.",
    deposit: "Aporte",
    withdrawal: "Retirada",
    date: "Data",
    goal: "Meta",
    account: "Conta",
    note: "Observação",
    amount: "Valor",
    emptyTitle: "Nenhuma movimentação encontrada",
    emptyDescription: "Os aportes e retiradas aparecerão aqui.",
  },
  goalDialog: {
    eyebrow: "Novo planejamento",
    createTitle: "Criar meta financeira",
    editTitle: "Editar meta financeira",
    description:
      "Defina o valor, prazo e ritmo de contribuição para transformar o objetivo em um plano executável.",
    name: "Nome da meta",
    namePlaceholder: "Ex.: Entrada do apartamento",
    descriptionLabel: "Descrição",
    descriptionPlaceholder: "Explique o objetivo e o que está incluído no valor planejado.",
    kind: "Tipo de planejamento",
    goal: "Objetivo",
    reserve: "Reserva",
    category: "Categoria",
    targetAmount: "Valor-alvo",
    currentAmount: "Valor inicial",
    monthlyContribution: "Aporte mensal planejado",
    targetDate: "Prazo desejado",
    account: "Conta vinculada",
    priority: "Prioridade",
    visual: "Identificação visual",
    cancel: "Cancelar",
    create: "Criar meta",
    save: "Salvar alterações",
    required: "Preencha todos os campos obrigatórios.",
    invalidTarget: "Informe um valor-alvo maior que zero.",
    invalidCurrent: "O valor inicial não pode ser negativo nem superar a meta.",
    invalidMonthly: "O aporte mensal não pode ser negativo.",
    successCreate: "Meta criada com sucesso.",
    successEdit: "Meta atualizada com sucesso.",
  },
  contributionDialog: {
    eyebrow: "Movimentação da meta",
    title: "Adicionar ou retirar valor",
    description:
      "Registre um aporte ou uma retirada para manter o progresso da meta atualizado.",
    goal: "Meta",
    type: "Movimentação",
    deposit: "Adicionar valor",
    withdrawal: "Retirar valor",
    amount: "Valor",
    date: "Data",
    account: "Conta de origem ou destino",
    note: "Observação",
    notePlaceholder: "Ex.: Aporte mensal de julho",
    cancel: "Cancelar",
    submit: "Registrar movimentação",
    required: "Preencha todos os campos obrigatórios.",
    invalidAmount: "Informe um valor maior que zero.",
    insufficient: "A retirada não pode superar o valor acumulado na meta.",
    successDeposit: "Valor adicionado à meta.",
    successWithdrawal: "Retirada registrada na meta.",
  },
  feedback: {
    paused: "Meta pausada.",
    resumed: "Meta retomada.",
    completed: "Meta marcada como concluída.",
  },
} as const;
