export const budgetsContent = {
  heading: {
    eyebrow: "Planejamento financeiro",
    title: "Orçamentos e categorias",
    description:
      "Defina limites mensais, acompanhe o consumo por categoria e mantenha seus gastos dentro do planejamento.",
    newBudget: "Novo orçamento",
    newCategory: "Nova categoria",
  },
  views: {
    budgets: "Orçamentos",
    categories: "Categorias",
  },
  summary: {
    planned: "Planejado no mês",
    spent: "Gasto realizado",
    available: "Ainda disponível",
    attention: "Categorias em atenção",
    plannedHint: "Soma dos limites definidos",
    spentHint: "Despesas confirmadas no período",
    availableHint: "Margem antes de atingir os limites",
    attentionHint: "Próximas ou acima do limite",
  },
  accessibility: {
    summary: "Resumo dos orçamentos",
    viewSelector: "Visualização do módulo",
    search: "Buscar orçamentos",
    closeDialog: "Fechar janela",
    tone: "Cor de identificação",
  },
  toolbar: {
    periodLabel: "Período analisado",
    searchLabel: "Buscar",
    statusLabel: "Estado",
    searchPlaceholder: "Buscar categoria ou descrição",
    allStatuses: "Todos os estados",
    healthy: "Dentro do limite",
    attention: "Em atenção",
    exceeded: "Limite excedido",
    previousMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    currentMonth: "Mês atual",
    clear: "Limpar filtros",
    copyPrevious: "Copiar mês anterior",
  },
  list: {
    eyebrow: "Controle mensal",
    title: "Orçamento por categoria",
    count: "categorias planejadas",
    planned: "Planejado",
    spent: "Gasto",
    available: "Disponível",
    used: "utilizado",
    edit: "Editar orçamento",
    emptyTitle: "Nenhum orçamento encontrado",
    emptyDescription:
      "Ajuste os filtros ou crie um limite mensal para começar a acompanhar esta categoria.",
  },
  status: {
    healthy: "Dentro do limite",
    attention: "Em atenção",
    exceeded: "Excedido",
  },
  insight: {
    eyebrow: "Leitura do mês",
    title: "Ritmo do orçamento",
    description:
      "Compare quanto do mês já passou com a parcela do orçamento utilizada até agora.",
    monthElapsed: "Mês percorrido",
    budgetUsed: "Orçamento utilizado",
    projected: "Projeção até o fim do mês",
    largestCategory: "Maior consumo",
    controlledTitle: "Ritmo controlado",
    controlledDescription:
      "O consumo está abaixo do ritmo do mês. Mantenha o planejamento atual.",
    warningTitle: "Atenção ao ritmo",
    warningDescription:
      "O consumo está avançando mais rápido que o mês. Revise as categorias em destaque.",
    allocationTitle: "Distribuição planejada",
    allocationDescription: "Participação de cada categoria no orçamento total.",
  },
  categories: {
    eyebrow: "Organização",
    title: "Categorias financeiras",
    description:
      "Personalize a forma como receitas e despesas são classificadas em todo o sistema.",
    expenses: "Categorias de despesas",
    incomes: "Categorias de receitas",
    active: "Ativa",
    inactive: "Inativa",
    default: "Padrão",
    custom: "Personalizada",
    deactivate: "Desativar",
    activate: "Ativar",
    expenseCount: "categorias de despesas",
    incomeCount: "categorias de receitas",
  },
  budgetDialog: {
    eyebrow: "Planejamento mensal",
    createTitle: "Criar orçamento",
    editTitle: "Editar orçamento",
    description: "Defina o limite e o ponto em que o sistema deve sinalizar atenção.",
    category: "Categoria",
    emptyCategories: "Nenhuma categoria disponível",
    limit: "Limite mensal",
    limitPlaceholder: "0,00",
    threshold: "Avisar a partir de",
    thresholdHint: "Percentual de uso que ativa o estado de atenção.",
    cancel: "Cancelar",
    create: "Criar orçamento",
    save: "Salvar alterações",
    required: "Preencha todos os campos obrigatórios.",
    invalidLimit: "Informe um limite maior que zero.",
    successCreate: "Orçamento criado com sucesso.",
    successEdit: "Orçamento atualizado com sucesso.",
  },
  categoryDialog: {
    eyebrow: "Classificação financeira",
    title: "Criar categoria",
    description: "Adicione uma categoria personalizada para organizar seus lançamentos.",
    name: "Nome da categoria",
    namePlaceholder: "Ex.: Pets",
    type: "Tipo",
    expense: "Despesa",
    income: "Receita",
    descriptionLabel: "Descrição",
    descriptionPlaceholder: "Explique quais lançamentos pertencem a esta categoria.",
    tone: "Identificação visual",
    cancel: "Cancelar",
    create: "Criar categoria",
    required: "Informe o nome e a descrição da categoria.",
    duplicate: "Já existe uma categoria com este nome.",
    success: "Categoria criada com sucesso.",
  },
  feedback: {
    copied: "Orçamentos do mês anterior copiados com sucesso.",
    nothingToCopy: "Não há orçamentos no mês anterior para copiar.",
    categoryActivated: "Categoria ativada.",
    categoryDeactivated: "Categoria desativada.",
  },
} as const;

export const monthNames = [
  "Janeiro",
  "Fevereiro",
  "Março",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro",
] as const;
