import type {
  ReceivableRecurrence,
  ReceivableStatus,
} from "@/types/recebimentos";

export const receivablesContent = {
  heading: {
    eyebrow: "Entradas previstas",
    title: "Recebimentos",
    description:
      "Acompanhe valores já recebidos, entradas esperadas e atrasos sem confundir previsão com dinheiro disponível.",
    newAction: "Novo recebimento",
  },
  summary: {
    received: "Recebido no mês",
    receivedHelper: "Valores efetivamente confirmados",
    expected: "A receber",
    expectedHelper: "Saldo previsto ainda não recebido",
    sevenDays: "Próximos 7 dias",
    sevenDaysHelper: "Entradas esperadas no curto prazo",
    overdue: "Em atraso",
    overdueHelper: "Recebimentos após a data prevista",
    recurring: "Receitas recorrentes",
    recurringHelper: "Entradas que se repetem automaticamente",
  },
  filters: {
    searchPlaceholder: "Buscar descrição, origem ou pagador",
    allStatuses: "Todos os status",
    allPeriods: "Todos os períodos",
    allCategories: "Todas as categorias",
    allAccounts: "Todas as contas",
    clear: "Limpar filtros",
    periods: {
      today: "Previsto para hoje",
      sevenDays: "Próximos 7 dias",
      month: "Neste mês",
      overdue: "Atrasados",
    },
  },
  list: {
    kicker: "Agenda de entradas",
    title: "Recebimentos cadastrados",
    countSuffix: "recebimentos encontrados",
    columns: {
      description: "Recebimento",
      expectedDate: "Data prevista",
      source: "Origem",
      account: "Conta de destino",
      status: "Status",
      remaining: "Saldo restante",
      actions: "Ações",
    },
    receiveAction: "Registrar recebimento",
    receivedAction: "Recebido",
    remaining: "Restante",
    receivedAmount: "Já recebido",
    recurring: "Recorrente",
    emptyTitle: "Nenhum recebimento encontrado",
    emptyDescription:
      "Ajuste os filtros ou adicione uma nova entrada prevista.",
  },
  insight: {
    kicker: "Previsão de entrada",
    title: "Fluxo esperado",
    description:
      "Veja quanto pode entrar nos próximos dias sem tratar valores previstos como saldo confirmado.",
    expectedThisMonth: "Previsto neste mês",
    confirmedRate: "Taxa já confirmada",
    recurringIncome: "Entradas recorrentes",
    nextReceipt: "Próximo recebimento",
    attentionTitle: "Previsão não é saldo",
    attentionDescription:
      "Considere apenas valores confirmados ao decidir quanto pode gastar ou reservar.",
  },
  newDialog: {
    eyebrow: "Nova entrada prevista",
    title: "Adicionar recebimento",
    description:
      "Registre um valor que já entrou ou que você espera receber em uma data futura.",
    closeAriaLabel: "Fechar cadastro de recebimento",
    fields: {
      description: "Descrição",
      descriptionPlaceholder: "Ex.: Pagamento de serviço",
      source: "Origem",
      sourcePlaceholder: "Ex.: Serviço freelance",
      payer: "Pagador",
      payerPlaceholder: "Nome opcional da pessoa ou empresa",
      category: "Categoria",
      amount: "Valor esperado",
      expectedDate: "Data prevista",
      account: "Conta de destino",
      recurrence: "Recorrência",
      notes: "Observações",
      notesPlaceholder: "Informações opcionais sobre este recebimento",
    },
    cancel: "Cancelar",
    submit: "Salvar recebimento",
    success: "Recebimento adicionado com sucesso.",
  },
  receiptDialog: {
    eyebrow: "Confirmação de entrada",
    title: "Registrar recebimento",
    description:
      "Confirme o valor que entrou. Recebimentos parciais mantêm o saldo restante previsto.",
    closeAriaLabel: "Fechar registro de recebimento",
    total: "Valor esperado",
    alreadyReceived: "Já recebido",
    remaining: "Saldo restante",
    fields: {
      amount: "Valor recebido agora",
      date: "Data do recebimento",
      account: "Conta de destino",
    },
    cancel: "Cancelar",
    submit: "Confirmar recebimento",
    successFull: "Recebimento marcado como concluído.",
    successPartial: "Recebimento parcial registrado.",
  },
  statuses: {
    pending: "Pendente",
    overdue: "Atrasado",
    partial: "Parcial",
    received: "Recebido",
  } satisfies Record<ReceivableStatus, string>,
  recurrences: {
    none: "Sem recorrência",
    weekly: "Semanal",
    monthly: "Mensal",
    yearly: "Anual",
  } satisfies Record<ReceivableRecurrence, string>,
  categories: [
    "Serviços",
    "Vendas",
    "Rendimentos",
    "Reembolsos",
    "Aluguel",
    "Presentes",
    "Outros",
  ],
  validation: {
    required: "Preencha os campos obrigatórios.",
    positiveAmount: "Informe um valor maior que zero.",
    receiptLimit: "O valor recebido não pode superar o saldo restante.",
  },
} as const;
