import type { ProjectionScenario, ReportPeriod } from "@/types/relatorios";

export const reportsContent = {
  heading: {
    eyebrow: "Análises financeiras",
    title: "Relatórios e projeção financeira",
    description:
      "Entenda para onde seu dinheiro está indo, compare períodos e antecipe o impacto dos próximos compromissos.",
    export: "Exportar CSV",
    print: "Imprimir relatório",
  },
  views: {
    reports: "Relatórios",
    projection: "Projeção financeira",
  },
  toolbar: {
    period: "Período analisado",
    scenario: "Cenário da projeção",
    currentMonth: "Mês atual",
    lastThreeMonths: "Últimos 3 meses",
    lastSixMonths: "Últimos 6 meses",
    year: "Ano atual",
  },
  summary: {
    income: "Receitas no período",
    expenses: "Despesas no período",
    result: "Resultado financeiro",
    savingsRate: "Taxa de economia",
    averageIncome: "Média mensal de entradas",
    averageExpenses: "Média mensal de saídas",
    positiveResult: "Saldo positivo no período",
    negativeResult: "Despesas acima das receitas",
    savingsHelper: "Parcela das receitas que permaneceu disponível",
  },
  cashFlow: {
    title: "Evolução de entradas e saídas",
    description: "Comparação mensal do fluxo financeiro no período selecionado.",
    income: "Entradas",
    expenses: "Saídas",
    result: "Resultado",
    bestMonth: "Melhor resultado",
    worstMonth: "Maior pressão financeira",
  },
  categories: {
    title: "Despesas por categoria",
    description: "Distribuição dos gastos concluídos no mês atual.",
    empty: "Nenhuma despesa encontrada para o período.",
    total: "Total analisado",
  },
  budget: {
    title: "Planejado versus realizado",
    description: "Comparação entre os limites definidos e os gastos já concluídos.",
    planned: "Planejado",
    actual: "Realizado",
    available: "Disponível",
    exceeded: "Excedido",
    healthy: "Dentro do limite",
    attention: "Em atenção",
  },
  accounts: {
    title: "Distribuição do saldo",
    description: "Participação de cada conta no patrimônio financeiro atual.",
    total: "Saldo total",
  },
  health: {
    title: "Leitura da saúde financeira",
    description: "Indicadores simples para orientar as próximas decisões.",
    savingsRate: "Taxa de economia",
    commitments: "Compromissos sobre a renda",
    emergencyCoverage: "Cobertura da reserva",
    budgetUse: "Uso do orçamento",
    positiveSavings: "Uma taxa acima de 20% cria espaço para reservas e objetivos.",
    attentionSavings: "Procure preservar uma parte maior das entradas nos próximos meses.",
    commitmentHealthy: "Os compromissos fixos permanecem em uma faixa administrável.",
    commitmentAttention: "Uma parcela elevada da renda já está comprometida antes dos gastos variáveis.",
    emergencyPositive: "A reserva já cobre pelo menos três meses de despesas essenciais.",
    emergencyAttention: "A proteção atual ainda é pequena para absorver imprevistos maiores.",
    budgetHealthy: "O consumo do orçamento acompanha o ritmo do mês.",
    budgetAttention: "Os gastos estão avançando mais rápido que o período disponível.",
    recommendationsTitle: "Prioridades sugeridas",
    recommendationDebt: "Reduzir primeiro dívidas com juros altos libera caixa nos próximos meses.",
    recommendationReserve: "Direcionar aportes constantes para a reserva aumenta sua segurança financeira.",
    recommendationSubscriptions: "Revisar assinaturas de baixo uso pode reduzir custos recorrentes.",
  },
  projection: {
    title: "Projeção dos próximos 12 meses",
    description:
      "Estimativa baseada nos compromissos cadastrados, renda média e cenário escolhido.",
    startingBalance: "Saldo inicial",
    endingBalance: "Saldo ao fim da projeção",
    totalIncome: "Entradas projetadas",
    totalExpenses: "Saídas projetadas",
    lowestBalance: "Menor saldo previsto",
    month: "Mês",
    income: "Entradas",
    essential: "Contas essenciais",
    subscriptions: "Assinaturas",
    debts: "Dívidas",
    installments: "Parcelamentos",
    goals: "Metas e reservas",
    variable: "Gastos variáveis",
    expenses: "Saídas totais",
    result: "Resultado",
    balance: "Saldo projetado",
    chartTitle: "Trajetória do saldo",
    chartDescription: "Como o saldo total pode evoluir ao longo dos próximos meses.",
    commitmentsTitle: "Composição mensal inicial",
    commitmentsDescription: "Valores usados como base para a primeira competência da projeção.",
    risksTitle: "Alertas da projeção",
    negativeMonth: "O saldo mensal fica negativo em pelo menos uma competência.",
    negativeBalance: "O patrimônio projetado pode ficar negativo dentro do período analisado.",
    stableProjection: "O cenário mantém saldo positivo durante os 12 meses.",
    debtRelief: "O encerramento de parcelas reduz gradualmente os compromissos mensais.",
    estimateDisclaimer:
      "A projeção é uma estimativa de planejamento. Valores reais podem mudar conforme renda, juros, reajustes e novos gastos.",
  },
  scenarios: {
    conservative: {
      label: "Conservador",
      helper: "Receitas 10% menores e despesas 5% maiores",
    },
    realistic: {
      label: "Realista",
      helper: "Mantém a renda média e os compromissos atuais",
    },
    optimistic: {
      label: "Otimista",
      helper: "Receitas 8% maiores e despesas 4% menores",
    },
  } satisfies Record<ProjectionScenario, { label: string; helper: string }>,
  periods: {
    "current-month": "Julho de 2026",
    "last-3-months": "Maio a julho de 2026",
    "last-6-months": "Fevereiro a julho de 2026",
    year: "Janeiro a julho de 2026",
  } satisfies Record<ReportPeriod, string>,
  feedback: {
    exported: "Relatório exportado em CSV.",
  },
  accessibility: {
    views: "Alternar entre relatórios e projeção",
    summary: "Resumo financeiro do período",
    cashFlowChart: "Gráfico de entradas e saídas",
    projectionChart: "Gráfico da projeção de saldo",
  },
} as const;
